package: iwcc
version: '0.0.1'
author: Ingo Winter
supportpage: https://redaxo.org/support/community/#slack

requires:
    redaxo: '^5.8'

page:
    title: 'translate:iwcc_title'
    perm: iw_cookie_consent[]
    pjax: true
    icon: rex-icon fa fa-coffee
    subpages:
        cookiegroup:
            title: 'translate:iwcc_cookiegroups'
        cookie:
            title: 'translate:iwcc_cookies'
        text:
            title: 'translate:iwcc_texts'
        domain:
            title: 'translate:iwcc_domains'